# Generated by Django 3.1.4 on 2021-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('hora', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
