# Generated by Django 3.1.4 on 2021-02-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombrecorto', models.CharField(max_length=30)),
                ('image', models.ImageField(default='null', upload_to='')),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
